[package]
name = "esdicawt"
edition.workspace = true
version.workspace = true
description = "SD-CWT"
authors.workspace = true

[features]
default = []
pem = ["dep:pkcs8", "pkcs8?/pem"]
der = ["dep:pkcs8"]
ed25519 = ["cose-key-confirmation/ed25519"]
p256 = ["cose-key-confirmation/p256"]
p384 = ["cose-key-confirmation/p384"]
test-utils = ["dep:ed25519-dalek", "dep:p256", "dep:sha2", "cose-key-confirmation/ed25519", "cose-key-confirmation/p256", "cose-key-confirmation/p384"]

[dependencies]
esdicawt-spec.workspace = true
cose-key-confirmation.workspace = true
signature = { workspace = true, features = ["std", "digest"] }
digest.workspace = true
rand_core = { workspace = true, features = ["std"] }
getrandom = { workspace = true, features = ["js"] }
ciborium.workspace = true
thiserror.workspace = true
serde.workspace = true
pkcs8 = { workspace = true, optional = true }
tailcall.workspace = true

sha2 = { optional = true, workspace = true }
time = { workspace = true, features = ["wasm-bindgen"] }
ed25519-dalek = { optional = true, workspace = true, features = ["rand_core", "pem", "serde"] }
p256 = { optional = true, workspace = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
js-sys = "0.3"

[dev-dependencies]
esdicawt = { workspace = true, features = ["pem", "der", "test-utils"] }
serde = { workspace = true, features = ["derive"] }
cose-key-confirmation = { workspace = true, features = ["ed25519", "p256", "p384"] }
rand_chacha.workspace = true
sha2.workspace = true
thiserror.workspace = true
wasm-bindgen-test.workspace = true

[lints]
workspace = true
